version: '3.9'  

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${DOCMOST_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-docmost
    
  docmost:
    image: docmost/docmost:0.6
    container_name: docmost
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: ${DOCMOST_SECRET} 
      DATABASE_URL: 'postgresql://docmost:${DOCMOST_DB_PASSWORD}@db:5432/docmost?schema=public' 
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    volumes:
      - docmost:/app/data/storage
    networks:
      - app-docmost
  
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - app-docmost
      
volumes:
  docmost:
  db_data:
  redis_data:

networks:
  app-docmost:
    driver: bridge
