version: '3.9'  

services:
  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app_pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
  
networks:
  app_pgadmin:
  driver: bridge
