version: "3.9"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_MONITOR_ONLY: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 ubuntu-container # docker hub container to watch, can add more using space between containers 
    
